---
title: "Our World in Data: Key Crop Yields."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Our World in Data: Key Crop Yields.}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6.5,
  fig.height = 5
)
```

```{r setup}
library(cwdata)
library(tibble)
key_crop_yields
```

This packages  provides the `key_crop_yields` dataset, which contains crop yields for countries over time. The yields are measured in tonnes per hectare for elevn crops (`r glue::glue_collapse(unique(key_crop_yields$crop),sep = ", ", last = " and ")`). This data is sourced from [Our World].

# Exploration of the data

Crop production in Australia:

```{r}
library(ggplot2)
library(dplyr)
key_crop_yields %>% 
  filter(country == "Australia") %>% 
  ggplot(aes(x = year, y = tonnes_per_hectare)) +
  geom_line() +
  facet_wrap(vars(crop), scales = "free_y") +
  labs(title = "Australian crop production",
       x = "Time in years",
       y = "Tonnes per hectare") +
  theme_bw()
```

